name: unit_test
on: [ push, pull_request ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install valgrind
        run: sudo apt update && sudo apt install -y valgrind
      - name: make tests
        run: make tests